baseURL = "http://groktop.us/"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "groktopus | learning stuff about things"
theme = "blogge"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 2
#  [[menu.main]]
#    name = "Contact"
#    url= "contact"
#    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Magnus Hedemark"
  authorThumb = "images/authors/magnus.png"
#  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
#  authorPhone = "+33-257634 534"
  instaUsername = "magnus919"
#  facebookUsername = "mary_astor"
  twitterUsername = "magnus919"
  linkedinUsername = "hedemark"
  blogTitle = "Articles"
  blogSubTitle = "View the latest articles"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
#  fabformURL  = "9AJk8ro"
#  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
